var express=require('express');
var router=express.Router();

let citykey=[{City:'Aborlan',Province:'Palawan'},
{City:'Abra de Ilog',Province:'Occidental Mindoro'},
{City:'Abucay',Province:'Bataan'},
{City:'Abulug',Province:'Cagayan'},
{City:'Abuyog',Province:'Leyte'},
{City:'Agdangan',Province:'Quezon'},
{City:'Aglipay',Province:'Quirino'},
{City:'Agno',Province:'Pangasinan'},
{City:'Agoncillo',Province:'Batangas'},
{City:'Agoo',Province:'La Union'},
{City:'Aguilar',Province:'Pangasinan'},
{City:'Ajuy',Province:'Iloilo'},
{City:'Alabel',Province:'Sarangani'},
{City:'Alamada',Province:'Cotabato'},
{City:'Alaminos',Province:'Pangasinan'},
{City:'Alaminos',Province:'Laguna'},
{City:'Alangalang',Province:'Leyte'},
{City:'Albuera',Province:'Leyte'},
{City:'Alcala',Province:'Pangasinan'},
{City:'Alcala',Province:'Cagayan'},
{City:'Alcantara',Province:'Cebu'},
{City:'Alfonso',Province:'Cavite'},
{City:'Aliaga',Province:'Nueva Ecija'},
{City:'Alicia',Province:'Isabela'},
{City:'Alicia',Province:'Zamboanga Sibugay'},
{City:'Alimodian',Province:'Iloilo'},
{City:'Allacapan',Province:'Cagayan'},
{City:'Aloguinsan',Province:'Cebu'},
{City:'Aloran',Province:'Misamis Occidental'},
{City:'Alubijid',Province:'Misamis Oriental'},
{City:'Amadeo',Province:'Cavite'},
{City:'Amulung',Province:'Cagayan'},
{City:'Anda',Province:'Pangasinan'},
{City:'Anda',Province:'Bohol'},
{City:'Angadanan',Province:'Isabela'},
{City:'Angat',Province:'Bulacan'},
{City:'Angeles City',Province:'Angeles'},
{City:'Angono',Province:'Rizal'},
{City:'Anilao',Province:'Iloilo'},
{City:'Antipolo',Province:'Rizal'},
{City:'Apalit',Province:'Pampanga'},
{City:'Aparri',Province:'Cagayan'},
{City:'Arayat',Province:'Pampanga'},
{City:'Argao',Province:'Cebu'},
{City:'Aringay',Province:'La Union'},
{City:'Aritao',Province:'Nueva Vizcaya'},
{City:'Aroroy',Province:'Masbate'},
{City:'Asingan',Province:'Pangasinan'},
{City:'Asturias',Province:'Cebu'},
{City:'Atimonan',Province:'Quezon'},
{City:'Aurora',Province:'Quezon'},
{City:'Aurora',Province:'Zamboanga del Sur'},
{City:'Aurora',Province:'Isabela'},
{City:'Ayungon',Province:'Negros Oriental'},
{City:'Baao',Province:'Camarines Sur'},
{City:'Babatngon',Province:'Leyte'},
{City:'Bacacay',Province:'Albay'},
{City:'Bacarra',Province:'Ilocos Norte'},
{City:'Baclayon',Province:'Bohol'},
{City:'Bacnotan',Province:'La Union'},
{City:'Baco',Province:'Oriental Mindoro'},
{City:'Bacolod',Province:'Bacolod'},
{City:'Bacolor',Province:'Pampanga'},
{City:'Bacong',Province:'Negros Oriental'},
{City:'Bacoor',Province:'Cavite'},
{City:'Badian',Province:'Cebu'},
{City:'Badoc',Province:'Ilocos Norte'},
{City:'Bagabag',Province:'Nueva Vizcaya'},
{City:'Baganga',Province:'Davao Oriental'},
{City:'Baggao',Province:'Cagayan'},
{City:'Bago',Province:'Negros Occidental'},
{City:'Baguio City',Province:'Baguio'},
{City:'Bagumbayan',Province:'Maguindanao'},
{City:'Bais',Province:'Negros Oriental'},
{City:'Balabac',Province:'Palawan'},
{City:'Balagtas',Province:'Bulacan'},
{City:'Balamban',Province:'Cebu'},
{City:'Balanga',Province:'Bataan'},
{City:'Balaoan',Province:'La Union'},
{City:'Balasan',Province:'Iloilo'},
{City:'Balatan',Province:'Camarines Sur'},
{City:'Balayan',Province:'Batangas'},
{City:'Baler',Province:'Aurora'},
{City:'Balete',Province:'Aklan'},
{City:'Balimbing',Province:'Tawi-Tawi'},
{City:'Balimbing',Province:'Lanao del Norte'},
{City:'Balindong',Province:'Lanao del Sur'},
{City:'Balingasag',Province:'Misamis Oriental'},
{City:'Baliuag',Province:'Bulacan'},
{City:'Ballesteros',Province:'Cagayan'},
{City:'Balud',Province:'Masbate'},
{City:'Balungao',Province:'Pangasinan'},
{City:'Bamban',Province:'Tarlac'},
{City:'Bambang',Province:'Nueva Vizcaya'},
{City:'Banate',Province:'Iloilo'},
{City:'Banaybanay',Province:'Davao Oriental'},
{City:'Banga',Province:'South Cotabato'},
{City:'Bañga',Province:'Aklan'},
{City:'Bangar',Province:'La Union'},
{City:'Bangued',Province:'Abra'},
{City:'Bani',Province:'Pangasinan'},
{City:'Banisilan',Province:'Cotabato'},
{City:'Bansalan',Province:'Davao del Sur'},
{City:'Bantacan',Province:'Compostela Valley'},
{City:'Bantay',Province:'Ilocos Sur'},
{City:'Bantayan',Province:'Cebu'},
{City:'Baras',Province:'Rizal'},
{City:'Barili',Province:'Cebu'},
{City:'Barira',Province:'Maguindanao'},
{City:'Barobo',Province:'Surigao del Sur'},
{City:'Barotac Nuevo',Province:'Iloilo'},
{City:'Barotac Viejo',Province:'Iloilo'},
{City:'Barugo',Province:'Leyte'},
{City:'Basco',Province:'Batanes'},
{City:'Basey',Province:'Samar'},
{City:'Basilisa',Province:'Surigao del Norte'},
{City:'Basista',Province:'Pangasinan'},
{City:'Basud',Province:'Camarines Norte'},
{City:'Batac',Province:'Ilocos Norte'},
{City:'Batan',Province:'Aklan'},
{City:'Batangas',Province:'Batangas'},
{City:'Batarasa',Province:'Palawan'},
{City:'Bato',Province:'Camarines Sur'},
{City:'Batobato',Province:'Davao Oriental'},
{City:'Bauan',Province:'Batangas'},
{City:'Bauang',Province:'La Union'},
{City:'Bauko',Province:'Mountain'},
{City:'Bautista',Province:'Pangasinan'},
{City:'Bay',Province:'Laguna'},
{City:'Bayawan',Province:'Negros Oriental'},
{City:'Baybay',Province:'Leyte'},
{City:'Bayog',Province:'Zamboanga del Sur'},
{City:'Bayombong',Province:'Nueva Vizcaya'},
{City:'Bayugan',Province:'Agusan del Sur'},
{City:'Benito Soliven',Province:'Isabela'},
{City:'Binalbagan',Province:'Negros Occidental'},
{City:'Binalonan',Province:'Pangasinan'},
{City:'Biñan',Province:'Laguna'},
{City:'Binangonan',Province:'Rizal'},
{City:'Binmaley',Province:'Pangasinan'},
{City:'Bislig',Province:'Surigao del Sur'},
{City:'Boac',Province:'Marinduque'},
{City:'Bocaue',Province:'Bulacan'},
{City:'Bogo',Province:'Cebu'},
{City:'Bolinao',Province:'Pangasinan'},
{City:'Bongabon',Province:'Nueva Ecija'},
{City:'Bongabong',Province:'Oriental Mindoro'},
{City:'Bongao',Province:'Tawi-Tawi'},
{City:'Bonifacio',Province:'Misamis Occidental'},
{City:'Bontoc',Province:'Southern Leyte'},
{City:'Bontoc',Province:'Mountain'},
{City:'Borbon',Province:'Cebu'},
{City:'Borongan',Province:'Eastern Samar'},
{City:'Botolan',Province:'Zambales'},
{City:'Brookes Point',Province:'Palawan'},
{City:'Buenavista',Province:'Agusan del Norte'},
{City:'Buenavista',Province:'Iloilo'},
{City:'Buenavista',Province:'Quezon'},
{City:'Bugallon',Province:'Pangasinan'},
{City:'Bugasong',Province:'Antique'},
{City:'Buguey',Province:'Cagayan'},
{City:'Buguias',Province:'Benguet'},
{City:'Buhi',Province:'Camarines Sur'},
{City:'Bula',Province:'Camarines Sur'},
{City:'Bulacan',Province:'Bulacan'},
{City:'Bulalacao',Province:'Oriental Mindoro'},
{City:'Bulan',Province:'Sorsogon'},
{City:'Buldon',Province:'Maguindanao'},
{City:'Buluan',Province:'Maguindanao'},
{City:'Bunawan',Province:'Agusan del Sur'},
{City:'Burauen',Province:'Leyte'},
{City:'Butuan',Province:'Butuan'},
{City:'Buug',Province:'Zamboanga Sibugay'},
{City:'Cabadbaran',Province:'Agusan del Norte'},
{City:'Cabagan',Province:'Isabela'},
{City:'Cabanatuan City',Province:'Nueva Ecija'},
{City:'Cabanglasan',Province:'Bukidnon'},
{City:'Cabarroguis',Province:'Quirino'},
{City:'Cabatuan',Province:'Iloilo'},
{City:'Cabatuan',Province:'Isabela'},
{City:'Cabiao',Province:'Nueva Ecija'},
{City:'Cabugao',Province:'Ilocos Sur'},
{City:'Cabuyao',Province:'Laguna'},
{City:'Cadiz',Province:'Negros Occidental'},
{City:'Cagayan de Oro',Province:'Cagayan de Oro'},
{City:'Cainta',Province:'Rizal'},
{City:'Calabanga',Province:'Camarines Sur'},
{City:'Calabayan',Province:'Isabela'},
{City:'Calaca',Province:'Batangas'},
{City:'Calapan',Province:'Oriental Mindoro'},
{City:'Calape',Province:'Bohol'},
{City:'Calasiao',Province:'Pangasinan'},
{City:'Calatagan',Province:'Batangas'},
{City:'Calatrava',Province:'Negros Occidental'},
{City:'Calauag',Province:'Quezon'},
{City:'Calauan',Province:'Laguna'},
{City:'Calbayog City',Province:'Samar'},
{City:'Calinog',Province:'Iloilo'},
{City:'Calintaan',Province:'Occidental Mindoro'},
{City:'Caloocan City',Province:'Caloocan'},
{City:'Calubian',Province:'Leyte'},
{City:'Calumpit',Province:'Bulacan'},
{City:'Caluya',Province:'Antique'},
{City:'Camalig',Province:'Albay'},
{City:'Cambanugoy',Province:'Davao del Norte'},
{City:'Camiling',Province:'Tarlac'},
{City:'Canaman',Province:'Camarines Sur'},
{City:'Candaba',Province:'Pampanga'},
{City:'Candelaria',Province:'Quezon'},
{City:'Candijay',Province:'Bohol'},
{City:'Candon',Province:'Ilocos Sur'},
{City:'Canlaon',Province:'Negros Oriental'},
{City:'Cantilan',Province:'Surigao del Sur'},
{City:'Capalonga',Province:'Camarines Norte'},
{City:'Capas',Province:'Tarlac'},
{City:'Capoocan',Province:'Leyte'},
{City:'Caraga',Province:'Davao Oriental'},
{City:'Caramoan',Province:'Camarines Sur'},
{City:'Caramoran',Province:'Catanduanes'},
{City:'Carcar',Province:'Cebu'},
{City:'Cardona',Province:'Rizal'},
{City:'Caridad',Province:'Cavite'},
{City:'Carigara',Province:'Leyte'},
{City:'Carles',Province:'Iloilo'},
{City:'Carmen',Province:'Cotabato'},
{City:'Carmen',Province:'Davao del Norte'},
{City:'Carmen',Province:'Bohol'},
{City:'Carmona',Province:'Cavite'},
{City:'Carranglan',Province:'Nueva Ecija'},
{City:'Casiguran',Province:'Sorsogon'},
{City:'Castilla',Province:'Sorsogon'},
{City:'Castillejos',Province:'Zambales'},
{City:'Cataingan',Province:'Masbate'},
{City:'Catanauan',Province:'Quezon'},
{City:'Catarman',Province:'Northern Samar'},
{City:'Catbalogan',Province:'Samar'},
{City:'Cateel',Province:'Davao Oriental'},
{City:'Catmon',Province:'Cebu'},
{City:'Catubig',Province:'Northern Samar'},
{City:'Cavite City',Province:'Cavite'},
{City:'Cawayan',Province:'Negros Occidental'},
{City:'Cawayan',Province:'Masbate'},
{City:'Cebu City',Province:'Cebu'},
{City:'City of Calamba',Province:'Laguna'},
{City:'City of Isabela',Province:'Basilan'},
{City:'City of Parañaque',Province:'Parañaque'},
{City:'Clarin',Province:'Misamis Occidental'},
{City:'Claveria',Province:'Misamis Oriental'},
{City:'Claveria',Province:'Masbate'},
{City:'Claveria',Province:'Surigao del Norte'},
{City:'Claveria',Province:'Cagayan'},
{City:'Cogan',Province:'Cebu'},
{City:'Columbio',Province:'Sultan Kudarat'},
{City:'Compostela',Province:'Compostela Valley'},
{City:'Concepcion',Province:'Tarlac'},
{City:'Concepcion',Province:'Iloilo'},
{City:'Consolacion',Province:'Cebu'},
{City:'Cordon',Province:'Isabela'},
{City:'Corella',Province:'Bohol'},
{City:'Coron',Province:'Palawan'},
{City:'Cotabato',Province:'Cotabato'},
{City:'Cuartero',Province:'Capiz'},
{City:'Cuenca',Province:'Batangas'},
{City:'Culasi',Province:'Antique'},
{City:'Cuyapo',Province:'Nueva Ecija'},
{City:'Daanbantayan',Province:'Cebu'},
{City:'Daet',Province:'Camarines Norte'},
{City:'Dagami',Province:'Leyte'},
{City:'Dagupan City',Province:'Dagupan'},
{City:'Dalaguete',Province:'Cebu'},
{City:'Damulog',Province:'Bukidnon'},
{City:'Danao',Province:'Cebu'},
{City:'Dao',Province:'Capiz'},
{City:'Dapitan',Province:'Zamboanga del Norte'},
{City:'Daraga',Province:'Albay'},
{City:'Daram',Province:'Samar'},
{City:'Dasmariñas',Province:'Cavite'},
{City:'Dasol',Province:'Pangasinan'},
{City:'Datu Paglas',Province:'Maguindanao'},
{City:'Dauin',Province:'Negros Oriental'},
{City:'Dauis',Province:'Bohol'},
{City:'Davao',Province:'Davao'},
{City:'Diffun',Province:'Quirino'},
{City:'Digos',Province:'Davao del Sur'},
{City:'Dimataling',Province:'Zamboanga del Sur'},
{City:'Dinalupihan',Province:'Bataan'},
{City:'Dinas',Province:'Zamboanga del Sur'},
{City:'Dingle',Province:'Iloilo'},
{City:'Dingras',Province:'Ilocos Norte'},
{City:'Dipaculao',Province:'Aurora'},
{City:'Diplahan',Province:'Zamboanga Sibugay'},
{City:'Dipolog',Province:'Zamboanga del Norte'},
{City:'Dolores',Province:'Eastern Samar'},
{City:'Dolores',Province:'Quezon'},
{City:'Don Carlos',Province:'Bukidnon'},
{City:'Donsol',Province:'Sorsogon'},
{City:'Dueñas',Province:'Iloilo'},
{City:'Dulag',Province:'Leyte'},
{City:'Dumaguete City',Province:'Negros Oriental'},
{City:'Dumalag',Province:'Capiz'},
{City:'Dumalinao',Province:'Zamboanga del Sur'},
{City:'Dumangas',Province:'Iloilo'},
{City:'Dumanjog',Province:'Cebu'},
{City:'Dumarao',Province:'Capiz'},
{City:'Dumingag',Province:'Zamboanga del Sur'},
{City:'Dupax Del Norte',Province:'Nueva Vizcaya'},
{City:'Echague',Province:'Isabela'},
{City:'El Nido',Province:'Palawan'},
{City:'El Salvador',Province:'Misamis Oriental'},
{City:'Enrile',Province:'Cagayan'},
{City:'Escalante',Province:'Negros Occidental'},
{City:'Esperanza',Province:'Sultan Kudarat'},
{City:'Esperanza',Province:'Agusan del Sur'},
{City:'Estancia',Province:'Iloilo'},
{City:'Floridablanca',Province:'Pampanga'},
{City:'Gamu',Province:'Isabela'},
{City:'Gandara',Province:'Samar'},
{City:'Gapan',Province:'Nueva Ecija'},
{City:'Gasan',Province:'Marinduque'},
{City:'Gattaran',Province:'Cagayan'},
{City:'General Mamerto Natividad',Province:'Nueva Ecija'},
{City:'General Mariano Alvarez',Province:'Cavite'},
{City:'General Nakar',Province:'Quezon'},
{City:'General Santos',Province:'General Santos'},
{City:'General Tinio',Province:'Nueva Ecija'},
{City:'General Trias',Province:'Cavite'},
{City:'Gerona',Province:'Tarlac'},
{City:'Getafe',Province:'Bohol'},
{City:'Gingoog',Province:'Misamis Oriental'},
{City:'Glan',Province:'Sarangani'},
{City:'Gloria',Province:'Oriental Mindoro'},
{City:'Goa',Province:'Camarines Sur'},
{City:'Gonzaga',Province:'Cagayan'},
{City:'Guagua',Province:'Pampanga'},
{City:'Guambog',Province:'Compostela Valley'},
{City:'Gubat',Province:'Sorsogon'},
{City:'Guiguinto',Province:'Bulacan'},
{City:'Guihulñgan',Province:'Negros Oriental'},
{City:'Guimba',Province:'Nueva Ecija'},
{City:'Guimbal',Province:'Iloilo'},
{City:'Guinayangan',Province:'Quezon'},
{City:'Guindulman',Province:'Bohol'},
{City:'Guinobatan',Province:'Albay'},
{City:'Guiuan',Province:'Eastern Samar'},
{City:'Gumaca',Province:'Quezon'},
{City:'Gutalac',Province:'Zamboanga del Norte'},
{City:'Hagonoy',Province:'Bulacan'},
{City:'Hagonoy',Province:'Davao del Sur'},
{City:'Hamtic',Province:'Antique'},
{City:'Hermosa',Province:'Bataan'},
{City:'Hilongos',Province:'Leyte'},
{City:'Himamaylan',Province:'Negros Occidental'},
{City:'Hinatuan',Province:'Surigao del Sur'},
{City:'Hinigaran',Province:'Negros Occidental'},
{City:'Hinunangan',Province:'Southern Leyte'},
{City:'Iba',Province:'Zambales'},
{City:'Ibaan',Province:'Batangas'},
{City:'Ibajay',Province:'Aklan'},
{City:'Igbaras',Province:'Iloilo'},
{City:'Iguig',Province:'Cagayan'},
{City:'Ilagan',Province:'Isabela'},
{City:'Iligan',Province:'Iligan'},
{City:'Ilog',Province:'Negros Occidental'},
{City:'Iloilo',Province:'Iloilo'},
{City:'Imbatug',Province:'Bukidnon'},
{City:'Impasugong',Province:'Bukidnon'},
{City:'Imus',Province:'Cavite'},
{City:'Inabanga',Province:'Bohol'},
{City:'Indanan',Province:'Sulu'},
{City:'Indang',Province:'Cavite'},
{City:'Infanta',Province:'Quezon'},
{City:'Initao',Province:'Misamis Oriental'},
{City:'Ipil',Province:'Zamboanga Sibugay'},
{City:'Iriga City',Province:'Camarines Sur'},
{City:'Irosin',Province:'Sorsogon'},
{City:'Isabel',Province:'Leyte'},
{City:'Isabela',Province:'Negros Occidental'},
{City:'Isulan',Province:'Sultan Kudarat'},
{City:'Itogon',Province:'Benguet'},
{City:'Ivisan',Province:'Capiz'},
{City:'Jaen',Province:'Nueva Ecija'},
{City:'Jagna',Province:'Bohol'},
{City:'Jalajala',Province:'Rizal'},
{City:'Jamindan',Province:'Capiz'},
{City:'Janiuay',Province:'Iloilo'},
{City:'Jaro',Province:'Leyte'},
{City:'Jasaan',Province:'Misamis Oriental'},
{City:'Jimalalud',Province:'Negros Oriental'},
{City:'Jimenez',Province:'Misamis Occidental'},
{City:'Jinoba-an',Province:'Negros Occidental'},
{City:'Jolo',Province:'Sulu'},
{City:'Jones',Province:'Isabela'},
{City:'Jordan',Province:'Guimaras'},
{City:'Jose Abad Santos',Province:'Davao Occidental'},
{City:'Jose Pañganiban',Province:'Camarines Norte'},
{City:'Juban',Province:'Sorsogon'},
{City:'Kabacan',Province:'Cotabato'},
{City:'Kabankalan',Province:'Negros Occidental'},
{City:'Kabasalan',Province:'Zamboanga Sibugay'},
{City:'Kabugao',Province:'Apayao'},
{City:'Kadingilan',Province:'Bukidnon'},
{City:'Kalamansig',Province:'Sultan Kudarat'},
{City:'Kalibo',Province:'Aklan'},
{City:'Kalilangan',Province:'Bukidnon'},
{City:'Kalingalan Caluang',Province:'Sulu'},
{City:'Kananya',Province:'Leyte'},
{City:'Kapalong',Province:'Davao del Norte'},
{City:'Kapatagan',Province:'Lanao del Norte'},
{City:'Kasibu',Province:'Nueva Vizcaya'},
{City:'Katipunan',Province:'Zamboanga del Norte'},
{City:'Kawit',Province:'Cavite'},
{City:'Kiamba',Province:'Sarangani'},
{City:'Kibawe',Province:'Bukidnon'},
{City:'Kiblawan',Province:'Davao del Sur'},
{City:'Kidapawan',Province:'Cotabato'},
{City:'Kitaotao',Province:'Bukidnon'},
{City:'Koronadal',Province:'South Cotabato'},
{City:'Koronadal',Province:'South Cotabato'},
{City:'Kumalarang',Province:'Zamboanga del Sur'},
{City:'La Carlota',Province:'Negros Occidental'},
{City:'La Libertad',Province:'Negros Oriental'},
{City:'La Paz',Province:'Tarlac'},
{City:'La Paz',Province:'Agusan del Sur'},
{City:'La Trinidad',Province:'Benguet'},
{City:'Labangan',Province:'Zamboanga del Sur'},
{City:'Labason',Province:'Zamboanga del Norte'},
{City:'Lagawe',Province:'Ifugao'},
{City:'Lagonoy',Province:'Camarines Sur'},
{City:'Lala',Province:'Lanao del Norte'},
{City:'Lal-lo',Province:'Cagayan'},
{City:'Lambunao',Province:'Iloilo'},
{City:'Lamitan',Province:'Basilan'},
{City:'Languyan',Province:'Tawi-Tawi'},
{City:'Lantapan',Province:'Bukidnon'},
{City:'Laoac East',Province:'Pangasinan'},
{City:'Laoag',Province:'Ilocos Norte'},
{City:'Laoang',Province:'Northern Samar'},
{City:'Lapu-Lapu City',Province:'Lapu-Lapu'},
{City:'Lapuyan',Province:'Zamboanga del Sur'},
{City:'Las Navas',Province:'Northern Samar'},
{City:'Las Nieves',Province:'Agusan del Norte'},
{City:'Las Piñas City',Province:'Las Piñas'},
{City:'Lasam',Province:'Cagayan'},
{City:'Laur',Province:'Nueva Ecija'},
{City:'Laurel',Province:'Batangas'},
{City:'Lavezares',Province:'Northern Samar'},
{City:'Leganes',Province:'Iloilo'},
{City:'Legazpi City',Province:'Albay'},
{City:'Lemery',Province:'Batangas'},
{City:'Lemery',Province:'Iloilo'},
{City:'Leon',Province:'Iloilo'},
{City:'Leyte',Province:'Leyte'},
{City:'Lian',Province:'Batangas'},
{City:'Lianga',Province:'Surigao del Sur'},
{City:'Libacao',Province:'Aklan'},
{City:'Libmanan',Province:'Camarines Sur'},
{City:'Libon',Province:'Albay'},
{City:'Libona',Province:'Bukidnon'},
{City:'Libungan',Province:'Cotabato'},
{City:'Licab',Province:'Nueva Ecija'},
{City:'Ligao',Province:'Albay'},
{City:'Lilio',Province:'Laguna'},
{City:'Liloy',Province:'Zamboanga del Norte'},
{City:'Limay',Province:'Bataan'},
{City:'Lingayen',Province:'Pangasinan'},
{City:'Lingig',Province:'Surigao del Sur'},
{City:'Lipa City',Province:'Batangas'},
{City:'Llanera',Province:'Nueva Ecija'},
{City:'Lobo',Province:'Batangas'},
{City:'Lopez',Province:'Quezon'},
{City:'Loreto',Province:'Agusan del Sur'},
{City:'Los Baños',Province:'Laguna'},
{City:'Lower Tungawan',Province:'Zamboanga Sibugay'},
{City:'Lubao',Province:'Pampanga'},
{City:'Lucban',Province:'Quezon'},
{City:'Lucena',Province:'Lucena'},
{City:'Lumba-a-Bayabao',Province:'Lanao del Sur'},
{City:'Lumbang',Province:'Laguna'},
{City:'Luna',Province:'La Union'},
{City:'Lupao',Province:'Nueva Ecija'},
{City:'Lupi Viejo',Province:'Camarines Sur'},
{City:'Lupon',Province:'Davao Oriental'},
{City:'Lutayan',Province:'Maguindanao'},
{City:'Luuk',Province:'Sulu'},
{City:'M’lang',Province:'Cotabato'},
{City:'Maasin',Province:'Southern Leyte'},
{City:'Maasin',Province:'Sarangani'},
{City:'Maasin',Province:'Iloilo'},
{City:'Maayon',Province:'Capiz'},
{City:'Mabalacat',Province:'Pampanga'},
{City:'Mabinay',Province:'Negros Oriental'},
{City:'Mabini',Province:'Batangas'},
{City:'Mabuhay',Province:'Zamboanga Sibugay'},
{City:'Macabebe',Province:'Pampanga'},
{City:'Macalelon',Province:'Quezon'},
{City:'Maco',Province:'Compostela Valley'},
{City:'Maddela',Province:'Quirino'},
{City:'Madridejos',Province:'Cebu'},
{City:'Madridejos',Province:'Cebu'},
{City:'Magalang',Province:'Pampanga'},
{City:'Magpet',Province:'Cotabato'},
{City:'Magsaysay',Province:'Davao del Sur'},
{City:'Magsaysay',Province:'Occidental Mindoro'},
{City:'Magsaysay',Province:'Misamis Oriental'},
{City:'Magsingal',Province:'Ilocos Sur'},
{City:'Mahaplag',Province:'Leyte'},
{City:'Mahayag',Province:'Zamboanga del Sur'},
{City:'Maimbung',Province:'Sulu'},
{City:'Maitum',Province:'Sarangani'},
{City:'Majayjay',Province:'Laguna'},
{City:'Makati City',Province:'Makati'},
{City:'Makilala',Province:'Cotabato'},
{City:'Malabang',Province:'Lanao del Sur'},
{City:'Malabon',Province:'Malabon'},
{City:'Malalag',Province:'Davao del Sur'},
{City:'Malangas',Province:'Zamboanga Sibugay'},
{City:'Malapatan',Province:'Sarangani'},
{City:'Malasiqui',Province:'Pangasinan'},
{City:'Malay',Province:'Aklan'},
{City:'Malaybalay',Province:'Bukidnon'},
{City:'Malilipot',Province:'Albay'},
{City:'Malinao',Province:'Albay'},
{City:'Malita',Province:'Davao Occidental'},
{City:'Mallig',Province:'Isabela'},
{City:'Malolos',Province:'Bulacan'},
{City:'Maluñgun',Province:'Sarangani'},
{City:'Maluso',Province:'Basilan'},
{City:'Malvar',Province:'Batangas'},
{City:'Mambajao',Province:'Camiguin'},
{City:'Mamburao',Province:'Occidental Mindoro'},
{City:'Mambusao',Province:'Capiz'},
{City:'Mamungan',Province:'Lanao del Norte'},
{City:'Manaoag',Province:'Pangasinan'},
{City:'Manapla',Province:'Negros Occidental'},
{City:'Manay',Province:'Davao Oriental'},
{City:'Mandaluyong City',Province:'Mandaluyong'},
{City:'Mandaon',Province:'Masbate'},
{City:'Mandaue City',Province:'Mandaue'},
{City:'Mangaldan',Province:'Pangasinan'},
{City:'Mangatarem',Province:'Pangasinan'},
{City:'Manila',Province:'Manila'},
{City:'Manjuyod',Province:'Negros Oriental'},
{City:'Mankayan',Province:'Benguet'},
{City:'Manolo Fortich',Province:'Bukidnon'},
{City:'Mansalay',Province:'Oriental Mindoro'},
{City:'Manticao',Province:'Misamis Oriental'},
{City:'Manucan',Province:'Zamboanga del Norte'},
{City:'Mapandan',Province:'Pangasinan'},
{City:'Maragondon',Province:'Cavite'},
{City:'Maramag',Province:'Bukidnon'},
{City:'Marantao',Province:'Lanao del Sur'},
{City:'Marawi City',Province:'Lanao del Sur'},
{City:'Margosatubig',Province:'Zamboanga del Sur'},
{City:'Maria Aurora',Province:'Aurora'},
{City:'Maribojoc',Province:'Bohol'},
{City:'Marikina City',Province:'Marikina'},
{City:'Marilao',Province:'Bulacan'},
{City:'Mariveles',Province:'Bataan'},
{City:'Masantol',Province:'Pampanga'},
{City:'Masbate',Province:'Masbate'},
{City:'Masinloc',Province:'Zambales'},
{City:'Masiu',Province:'Lanao del Sur'},
{City:'Mataas Na Kahoy',Province:'Batangas'},
{City:'Matalam',Province:'Cotabato'},
{City:'Matalom',Province:'Leyte'},
{City:'Matanao',Province:'Davao del Sur'},
{City:'Matanog',Province:'Maguindanao'},
{City:'Mati',Province:'Davao Oriental'},
{City:'Matnog',Province:'Sorsogon'},
{City:'Mauban',Province:'Quezon'},
{City:'Mayantoc',Province:'Tarlac'},
{City:'Medellin',Province:'Cebu'},
{City:'Medina',Province:'Misamis Oriental'},
{City:'Mendez-Nuñez',Province:'Cavite'},
{City:'Mercedes',Province:'Camarines Norte'},
{City:'Merida',Province:'Leyte'},
{City:'Mexico',Province:'Pampanga'},
{City:'Meycauayan',Province:'Bulacan'},
{City:'Miagao',Province:'Iloilo'},
{City:'Midsalip',Province:'Zamboanga del Sur'},
{City:'Midsayap',Province:'Cotabato'},
{City:'Milagros',Province:'Masbate'},
{City:'Milaor',Province:'Camarines Sur'},
{City:'Minalabac',Province:'Camarines Sur'},
{City:'Minalin',Province:'Pampanga'},
{City:'Minglanilla',Province:'Cebu'},
{City:'Moalboal',Province:'Cebu'},
{City:'Mobo',Province:'Masbate'},
{City:'Mogpog',Province:'Marinduque'},
{City:'Moises Padilla',Province:'Negros Occidental'},
{City:'Molave',Province:'Zamboanga del Sur'},
{City:'Moncada',Province:'Tarlac'},
{City:'Mondragon',Province:'Northern Samar'},
{City:'Monkayo',Province:'Compostela Valley'},
{City:'Montevista',Province:'Compostela Valley'},
{City:'Morong',Province:'Rizal'},
{City:'Morong',Province:'Bataan'},
{City:'Mulanay',Province:'Quezon'},
{City:'Munai',Province:'Lanao del Norte'},
{City:'Muntinlupa City',Province:'Muntinlupa'},
{City:'Murcia',Province:'Negros Occidental'},
{City:'Nabas',Province:'Aklan'},
{City:'Nabua',Province:'Camarines Sur'},
{City:'Nabunturan',Province:'Compostela Valley'},
{City:'Naga',Province:'Cebu'},
{City:'Naga',Province:'Zamboanga Sibugay'},
{City:'Naga City',Province:'Naga'},
{City:'Nagcarlan',Province:'Laguna'},
{City:'Naguilian',Province:'La Union'},
{City:'Naguilian',Province:'Isabela'},
{City:'Naic',Province:'Cavite'},
{City:'Narra',Province:'Palawan'},
{City:'Narvacan',Province:'Ilocos Sur'},
{City:'Nasipit',Province:'Agusan del Norte'},
{City:'Nasugbu',Province:'Batangas'},
{City:'Naujan',Province:'Oriental Mindoro'},
{City:'Naval',Province:'Biliran'},
{City:'Navotas',Province:'Navotas'},
{City:'New Corella',Province:'Davao del Norte'},
{City:'New Panamao',Province:'Sulu'},
{City:'New Washington',Province:'Aklan'},
{City:'Norala',Province:'South Cotabato'},
{City:'Norzagaray',Province:'Bulacan'},
{City:'Noveleta',Province:'Cavite'},
{City:'Nueva Valencia',Province:'Guimaras'},
{City:'Numancia',Province:'Aklan'},
{City:'Oas',Province:'Albay'},
{City:'Obando',Province:'Bulacan'},
{City:'Ocampo',Province:'Camarines Sur'},
{City:'Odiongan',Province:'Romblon'},
{City:'Olongapo',Province:'Olongapo'},
{City:'Olutanga',Province:'Zamboanga Sibugay'},
{City:'Opol',Province:'Misamis Oriental'},
{City:'Orani',Province:'Bataan'},
{City:'Oras',Province:'Eastern Samar'},
{City:'Orion',Province:'Bataan'},
{City:'Ormoc',Province:'Ormoc'},
{City:'Oroquieta',Province:'Misamis Occidental'},
{City:'Oslob',Province:'Cebu'},
{City:'Oton',Province:'Iloilo'},
{City:'Ozamiz City',Province:'Misamis Occidental'},
{City:'Padre Burgos',Province:'Quezon'},
{City:'Padre Burgos',Province:'Southern Leyte'},
{City:'Padre Garcia',Province:'Batangas'},
{City:'Pagadian',Province:'Zamboanga del Sur'},
{City:'Pagalungan',Province:'Maguindanao'},
{City:'Pagbilao',Province:'Quezon'},
{City:'Pagsanjan',Province:'Laguna'},
{City:'Palapag',Province:'Northern Samar'},
{City:'Palauig',Province:'Zambales'},
{City:'Palayan City',Province:'Nueva Ecija'},
{City:'Palimbang',Province:'Sultan Kudarat'},
{City:'Palompon',Province:'Leyte'},
{City:'Pambujan',Province:'Northern Samar'},
{City:'Pamplona',Province:'Negros Oriental'},
{City:'Pamplona',Province:'Camarines Sur'},
{City:'Panabo',Province:'Davao del Norte'},
{City:'Pananaw',Province:'Sulu'},
{City:'Panay',Province:'Capiz'},
{City:'Pandan',Province:'Antique'},
{City:'Pandi',Province:'Bulacan'},
{City:'Pangantocan',Province:'Bukidnon'},
{City:'Panglao',Province:'Bohol'},
{City:'Paniqui',Province:'Tarlac'},
{City:'Panitan',Province:'Capiz'},
{City:'Pantabangan',Province:'Nueva Ecija'},
{City:'Pantao-Ragat',Province:'Lanao del Norte'},
{City:'Paombong',Province:'Bulacan'},
{City:'Paracale',Province:'Camarines Norte'},
{City:'Paracelis',Province:'Mountain'},
{City:'Parang',Province:'Maguindanao'},
{City:'Parang',Province:'Sulu'},
{City:'Pasacao',Province:'Camarines Sur'},
{City:'Pasay City',Province:'Pasay'},
{City:'Pasig City',Province:'Pasig'},
{City:'Passi',Province:'Iloilo'},
{City:'Pasuquin',Province:'Ilocos Norte'},
{City:'Pateros',Province:'Laguna'},
{City:'Patikul',Province:'Sulu'},
{City:'Patnongon',Province:'Antique'},
{City:'Pavia',Province:'Iloilo'},
{City:'Payabon',Province:'Negros Oriental'},
{City:'Payao',Province:'Zamboanga Sibugay'},
{City:'Peñablanca',Province:'Cagayan'},
{City:'Peñaranda',Province:'Nueva Ecija'},
{City:'Perez',Province:'Quezon'},
{City:'Pigcawayan',Province:'Cotabato'},
{City:'Pikit',Province:'Cotabato'},
{City:'Pila',Province:'Laguna'},
{City:'Pilar',Province:'Sorsogon'},
{City:'Pilar',Province:'Capiz'},
{City:'Pilar',Province:'Bataan'},
{City:'Pili',Province:'Camarines Sur'},
{City:'Pili',Province:'Camarines Sur'},
{City:'Pililla',Province:'Rizal'},
{City:'Pinamalayan',Province:'Oriental Mindoro'},
{City:'Pinamungahan',Province:'Cebu'},
{City:'Pinukpuk',Province:'Kalinga'},
{City:'Pio Duran',Province:'Albay'},
{City:'Placer',Province:'Masbate'},
{City:'Plaridel',Province:'Bulacan'},
{City:'Plaridel',Province:'Misamis Occidental'},
{City:'Poblacion',Province:'Cebu'},
{City:'Poblacion',Province:'Sultan Kudarat'},
{City:'Poblacion',Province:'Cebu'},
{City:'Poblacion',Province:'Cebu'},
{City:'Poblacion',Province:'Compostela Valley'},
{City:'Pola',Province:'Oriental Mindoro'},
{City:'Polanco',Province:'Zamboanga del Norte'},
{City:'Polangui',Province:'Albay'},
{City:'Polillo',Province:'Quezon'},
{City:'Polomolok',Province:'South Cotabato'},
{City:'Pongotan',Province:'Compostela Valley'},
{City:'Ponot',Province:'Zamboanga del Norte'},
{City:'Pontevedra',Province:'Negros Occidental'},
{City:'Pontevedra',Province:'Capiz'},
{City:'Porac',Province:'Pampanga'},
{City:'Pototan',Province:'Iloilo'},
{City:'Pozorrubio',Province:'Pangasinan'},
{City:'President Manuel Acuña Roxas',Province:'Zamboanga del Norte'},
{City:'President Quirino',Province:'Sultan Kudarat'},
{City:'President Roxas',Province:'Cotabato'},
{City:'President Roxas',Province:'Capiz'},
{City:'Proper Bansud',Province:'Oriental Mindoro'},
{City:'Prosperidad',Province:'Agusan del Sur'},
{City:'Puerto Galera',Province:'Oriental Mindoro'},
{City:'Puerto Princesa',Province:'Puerto Princesa'},
{City:'Pulilan',Province:'Bulacan'},
{City:'Pulupandan',Province:'Negros Occidental'},
{City:'Quezon',Province:'Bukidnon'},
{City:'Quezon',Province:'Palawan'},
{City:'Quezon',Province:'Nueva Ecija'},
{City:'Quezon City',Province:'Quezon'},
{City:'Ragay',Province:'Camarines Sur'},
{City:'Ramon',Province:'Isabela'},
{City:'Rapu-Rapu',Province:'Albay'},
{City:'Real',Province:'Quezon'},
{City:'Rizal',Province:'Nueva Ecija'},
{City:'Rizal',Province:'Occidental Mindoro'},
{City:'Robles',Province:'Negros Occidental'},
{City:'Rodriguez',Province:'Rizal'},
{City:'Romblon',Province:'Romblon'},
{City:'Rosales',Province:'Pangasinan'},
{City:'Rosario',Province:'Batangas'},
{City:'Rosario',Province:'Cavite'},
{City:'Rosario',Province:'La Union'},
{City:'Rosario',Province:'Agusan del Sur'},
{City:'Roseller Lim',Province:'Zamboanga Sibugay'},
{City:'Roxas',Province:'Palawan'},
{City:'Roxas',Province:'Isabela'},
{City:'Roxas',Province:'Oriental Mindoro'},
{City:'Roxas City',Province:'Capiz'},
{City:'Sablayan',Province:'Occidental Mindoro'},
{City:'Sagay',Province:'Negros Occidental'},
{City:'Sagnay',Province:'Camarines Sur'},
{City:'Saint Bernard',Province:'Southern Leyte'},
{City:'Salaman',Province:'Sultan Kudarat'},
{City:'Salay',Province:'Misamis Oriental'},
{City:'Salug',Province:'Zamboanga del Norte'},
{City:'Samal',Province:'Davao del Norte'},
{City:'Samal',Province:'Bataan'},
{City:'San Andres',Province:'Catanduanes'},
{City:'San Andres',Province:'Quezon'},
{City:'San Antonio',Province:'Nueva Ecija'},
{City:'San Antonio',Province:'Zambales'},
{City:'San Antonio',Province:'Quezon'},
{City:'San Carlos',Province:'Negros Occidental'},
{City:'San Carlos City',Province:'Pangasinan'},
{City:'San Dionisio',Province:'Iloilo'},
{City:'San Enrique',Province:'Iloilo'},
{City:'San Fabian',Province:'La Union'},
{City:'San Fernando',Province:'Pampanga'},
{City:'San Fernando',Province:'La Union'},
{City:'San Fernando',Province:'Cebu'},
{City:'San Fernando',Province:'Bukidnon'},
{City:'San Fernando',Province:'Camarines Sur'},
{City:'San Francisco',Province:'Agusan del Sur'},
{City:'San Francisco',Province:'Cebu'},
{City:'San Ildefonso',Province:'Bulacan'},
{City:'San Isidro',Province:'Nueva Ecija'},
{City:'San Isidro',Province:'Leyte'},
{City:'San Jacinto',Province:'Pangasinan'},
{City:'San Jacinto',Province:'Masbate'},
{City:'San Joaquin',Province:'Iloilo'},
{City:'San Jose',Province:'Occidental Mindoro'},
{City:'San Jose',Province:'Nueva Ecija'},
{City:'San Jose',Province:'Batangas'},
{City:'San Jose',Province:'Antique'},
{City:'San Jose',Province:'Camarines Sur'},
{City:'San Jose',Province:'Dinagat Islands'},
{City:'San Jose',Province:'Dinagat Islands'},
{City:'San Jose del Monte',Province:'Bulacan'},
{City:'San Juan',Province:'San Juan'},
{City:'San Juan',Province:'Batangas'},
{City:'San Juan',Province:'La Union'},
{City:'San Leonardo',Province:'Nueva Ecija'},
{City:'San Luis',Province:'Pampanga'},
{City:'San Luis',Province:'Batangas'},
{City:'San Luis',Province:'Agusan del Sur'},
{City:'San Luis',Province:'Aurora'},
{City:'San Manuel',Province:'Pangasinan'},
{City:'San Manuel',Province:'Isabela'},
{City:'San Marcelino',Province:'Zambales'},
{City:'San Mariano',Province:'Isabela'},
{City:'San Mateo',Province:'Rizal'},
{City:'San Mateo',Province:'Isabela'},
{City:'San Miguel',Province:'Bulacan'},
{City:'San Miguel',Province:'Surigao del Sur'},
{City:'San Miguel',Province:'Iloilo'},
{City:'San Narciso',Province:'Quezon'},
{City:'San Narciso',Province:'Zambales'},
{City:'San Nicolas',Province:'Ilocos Norte'},
{City:'San Nicolas',Province:'Pangasinan'},
{City:'San Pablo',Province:'Laguna'},
{City:'San Pascual',Province:'Batangas'},
{City:'San Pascual',Province:'Masbate'},
{City:'San Pedro',Province:'Laguna'},
{City:'San Quintin',Province:'Pangasinan'},
{City:'San Rafael',Province:'Bulacan'},
{City:'San Remigio',Province:'Cebu'},
{City:'San Remigio',Province:'Antique'},
{City:'San Roque',Province:'Northern Samar'},
{City:'San Simon',Province:'Pampanga'},
{City:'San Vicente',Province:'Palawan'},
{City:'Santa Ana',Province:'Pampanga'},
{City:'Santa Ana',Province:'Cagayan'},
{City:'Santa Barbara',Province:'Pangasinan'},
{City:'Santa Barbara',Province:'Iloilo'},
{City:'Santa Catalina',Province:'Negros Oriental'},
{City:'Santa Cruz',Province:'Laguna'},
{City:'Santa Cruz',Province:'Davao del Sur'},
{City:'Santa Cruz',Province:'Zambales'},
{City:'Santa Cruz',Province:'Marinduque'},
{City:'Santa Cruz',Province:'Ilocos Sur'},
{City:'Santa Cruz',Province:'Occidental Mindoro'},
{City:'Santa Cruz',Province:'Laguna'},
{City:'Santa Elena',Province:'Camarines Norte'},
{City:'Santa Fe',Province:'Cebu'},
{City:'Santa Ignacia',Province:'Tarlac'},
{City:'Santa Maria',Province:'Bulacan'},
{City:'Santa Maria',Province:'Davao del Sur'},
{City:'Santa Maria',Province:'Pangasinan'},
{City:'Santa Maria',Province:'Laguna'},
{City:'Santa Maria',Province:'Ilocos Sur'},
{City:'Santa Rita',Province:'Samar'},
{City:'Santa Rita',Province:'Pampanga'},
{City:'Santa Rosa',Province:'Laguna'},
{City:'Santa Rosa',Province:'Nueva Ecija'},
{City:'Santiago',Province:'Santiago'},
{City:'Santo Domingo',Province:'Nueva Ecija'},
{City:'Santo Domingo',Province:'Albay'},
{City:'Santo Domingo',Province:'Ilocos Sur'},
{City:'Santo Niño',Province:'South Cotabato'},
{City:'Santo Tomas',Province:'Batangas'},
{City:'Santo Tomas',Province:'Davao del Norte'},
{City:'Santo Tomas',Province:'Pampanga'},
{City:'Santo Tomas',Province:'La Union'},
{City:'Sapa Sapa',Province:'Tawi-Tawi'},
{City:'Saravia',Province:'Negros Occidental'},
{City:'Sariaya',Province:'Quezon'},
{City:'Science City of Muñoz',Province:'Nueva Ecija'},
{City:'Sergio Osmeña Sr',Province:'Zamboanga del Sur'},
{City:'Sexmoan',Province:'Pampanga'},
{City:'Shariff Aguak',Province:'Maguindanao'},
{City:'Siasi',Province:'Sulu'},
{City:'Siaton',Province:'Negros Oriental'},
{City:'Siay',Province:'Zamboanga Sibugay'},
{City:'Siayan',Province:'Zamboanga del Norte'},
{City:'Sibagat',Province:'Agusan del Sur'},
{City:'Sibalom',Province:'Antique'},
{City:'Sibonga',Province:'Cebu'},
{City:'Sibuco',Province:'Zamboanga del Norte'},
{City:'Sibulan',Province:'Negros Oriental'},
{City:'Sibutu',Province:'Tawi-Tawi'},
{City:'Sigaboy',Province:'Davao Oriental'},
{City:'Sigma',Province:'Capiz'},
{City:'Sikatuna',Province:'Bohol'},
{City:'Silang',Province:'Cavite'},
{City:'Silay',Province:'Negros Occidental'},
{City:'Simbahan',Province:'Sulu'},
{City:'Simunul',Province:'Tawi-Tawi'},
{City:'Sindangan',Province:'Zamboanga del Norte'},
{City:'Siniloan',Province:'Laguna'},
{City:'Siocon',Province:'Zamboanga del Norte'},
{City:'Sipalay',Province:'Negros Occidental'},
{City:'Sipocot',Province:'Camarines Sur'},
{City:'Siquijor',Province:'Siquijor'},
{City:'Siraway',Province:'Zamboanga del Norte'},
{City:'Sison',Province:'Pangasinan'},
{City:'Sitangkai',Province:'Tawi-Tawi'},
{City:'Socorro',Province:'Oriental Mindoro'},
{City:'Sogod',Province:'Southern Leyte'},
{City:'Sogod',Province:'Cebu'},
{City:'Solana',Province:'Cagayan'},
{City:'Solano',Province:'Nueva Vizcaya'},
{City:'Sorsogon',Province:'Sorsogon'},
{City:'South Upi',Province:'Maguindanao'},
{City:'Sual',Province:'Pangasinan'},
{City:'Subic',Province:'Zambales'},
{City:'Sulop',Province:'Davao del Sur'},
{City:'Sultan Kudarat',Province:'Maguindanao'},
{City:'Sumilao',Province:'Bukidnon'},
{City:'Sumisip',Province:'Basilan'},
{City:'Surallah',Province:'South Cotabato'},
{City:'Surigao',Province:'Surigao del Norte'},
{City:'Taal',Province:'Batangas'},
{City:'Tabaco',Province:'Albay'},
{City:'Tabango',Province:'Leyte'},
{City:'Tabogon',Province:'Cebu'},
{City:'Tabuk',Province:'Kalinga'},
{City:'Tabuk',Province:'Kalinga'},
{City:'Tacloban',Province:'Tacloban'},
{City:'Tacurong',Province:'Sultan Kudarat'},
{City:'Tagaytay',Province:'Cavite'},
{City:'Tagbilaran City',Province:'Bohol'},
{City:'Tagbina',Province:'Surigao del Sur'},
{City:'Tagkawayan',Province:'Quezon'},
{City:'Tago',Province:'Surigao del Sur'},
{City:'Tagoloan',Province:'Misamis Oriental'},
{City:'Tagudin',Province:'Ilocos Sur'},
{City:'Taguig City',Province:'Taguig'},
{City:'Tagum',Province:'Davao del Norte'},
{City:'Talacogon',Province:'Agusan del Sur'},
{City:'Talagutong',Province:'Davao Occidental'},
{City:'Talakag',Province:'Bukidnon'},
{City:'Talavera',Province:'Nueva Ecija'},
{City:'Talayan',Province:'Maguindanao'},
{City:'Talibon',Province:'Bohol'},
{City:'Talipao',Province:'Sulu'},
{City:'Talisay',Province:'Cebu'},
{City:'Talisay',Province:'Negros Occidental'},
{City:'Talisay',Province:'Batangas'},
{City:'Talusan',Province:'Zamboanga Sibugay'},
{City:'Tambulig',Province:'Zamboanga del Sur'},
{City:'Tampakan',Province:'South Cotabato'},
{City:'Tanauan',Province:'Batangas'},
{City:'Tanauan',Province:'Leyte'},
{City:'Tanay',Province:'Rizal'},
{City:'Tandag',Province:'Surigao del Sur'},
{City:'Tandubas',Province:'Tawi-Tawi'},
{City:'Tangub',Province:'Misamis Occidental'},
{City:'Tanjay',Province:'Negros Oriental'},
{City:'Tantangan',Province:'South Cotabato'},
{City:'Tanza',Province:'Cavite'},
{City:'Tapas',Province:'Capiz'},
{City:'Tarlac City',Province:'Tarlac'},
{City:'Tayabas',Province:'Quezon'},
{City:'Tayasan',Province:'Negros Oriental'},
{City:'Taysan',Province:'Batangas'},
{City:'Taytay',Province:'Rizal'},
{City:'Taytay',Province:'Palawan'},
{City:'Tayug',Province:'Pangasinan'},
{City:'Teresa',Province:'Rizal'},
{City:'Tiaong',Province:'Quezon'},
{City:'Tibigan',Province:'Bohol'},
{City:'Tigaon',Province:'Camarines Sur'},
{City:'Tigbauan',Province:'Iloilo'},
{City:'Tinambac',Province:'Camarines Sur'},
{City:'Tingloy',Province:'Batangas'},
{City:'Titay',Province:'Zamboanga Sibugay'},
{City:'Tiwi',Province:'Albay'},
{City:'Tobias Fornier',Province:'Antique'},
{City:'Toboso',Province:'Negros Occidental'},
{City:'Toledo',Province:'Cebu'},
{City:'Torrijos',Province:'Marinduque'},
{City:'Trece Martires City',Province:'Cavite'},
{City:'Trento',Province:'Agusan del Sur'},
{City:'Trinidad',Province:'Bohol'},
{City:'Tuao',Province:'Cagayan'},
{City:'Tuba',Province:'Baguio'},
{City:'Tubao',Province:'La Union'},
{City:'Tubod',Province:'Lanao del Norte'},
{City:'Tuburan',Province:'Cebu'},
{City:'Tucuran',Province:'Zamboanga del Sur'},
{City:'Tudela',Province:'Misamis Occidental'},
{City:'Tuguegarao',Province:'Cagayan'},
{City:'Tulunan',Province:'Cotabato'},
{City:'Tumauini',Province:'Isabela'},
{City:'Tupi',Province:'South Cotabato'},
{City:'Tuy',Province:'Batangas'},
{City:'Ubay',Province:'Bohol'},
{City:'Umingan',Province:'Pangasinan'},
{City:'Upi',Province:'Maguindanao'},
{City:'Urbiztondo',Province:'Pangasinan'},
{City:'Urdaneta',Province:'Pangasinan'},
{City:'Uson',Province:'Masbate'},
{City:'Valencia',Province:'Bukidnon'},
{City:'Valencia',Province:'Negros Oriental'},
{City:'Valenzuela',Province:'Valenzuela'},
{City:'Valladolid',Province:'Negros Occidental'},
{City:'Vallehermoso',Province:'Negros Oriental'},
{City:'Veruela',Province:'Agusan del Sur'},
{City:'Victoria',Province:'Tarlac'},
{City:'Victoria',Province:'Laguna'},
{City:'Victorias',Province:'Negros Occidental'},
{City:'Vigan',Province:'Ilocos Sur'},
{City:'Villaba',Province:'Leyte'},
{City:'Villanueva',Province:'Misamis Oriental'},
{City:'Villareal',Province:'Samar'},
{City:'Villasis',Province:'Pangasinan'},
{City:'Vintar',Province:'Ilocos Norte'},
{City:'Vinzons',Province:'Camarines Norte'},
{City:'Virac',Province:'Catanduanes'},
{City:'Wao',Province:'Lanao del Sur'},
{City:'Zamboanga City',Province:'Zamboanga'},
{City:'Zamboanguita',Province:'Negros Oriental'},
{City:'Zaragoza',Province:'Nueva Ecija'},
];

router.get('/',(req,res, next)=>{
    res.send({citykey});
});

router.get("/:id",(req,res, next)=>{
    const {id}=req.params;
    res.send(citykey[id]);
});

module.exports=router;